import { Car, Brand } from './types';

export const BRANDS: Brand[] = [
  { id: 1, name: 'Benz', logoText: 'Mercedes-Benz' },
  { id: 2, name: 'BMW', logoText: 'BMW' },
  { id: 3, name: 'Toyota', logoText: 'Toyota' },
  { id: 4, name: 'Hyundai', logoText: 'Hyundai' },
  { id: 5, name: 'Kia', logoText: 'Kia' },
  { id: 6, name: 'Porsche', logoText: 'Porsche' },
];

export const CARS: Car[] = [
  {
    id: 1,
    name: 'مرسدس بنز کلاس اس ۵۰۰',
    brand: 'Benz',
    modelYear: 2023,
    price: 15000000000,
    mileage: 12000,
    color: 'مشکی متالیک',
    gearbox: 'Automatic',
    fuelType: 'Petrol',
    description: 'شاهکار مهندسی آلمان، فول آپشن، دارای سیستم صوتی برمستر، صندلی‌های ماساژور و رادار کامل. بدون رنگ و خط و خش.',
    images: [
      { url: 'https://picsum.photos/id/111/800/600', alt: 'Benz S Class Front' },
      { url: 'https://picsum.photos/id/133/800/600', alt: 'Benz S Class Interior' },
      { url: 'https://picsum.photos/id/183/800/600', alt: 'Benz S Class Side' },
    ],
    isFeatured: true,
    paintStatus: 'بدون رنگ',
    chassisStatus: 'پلمپ',
    bodyStatus: 'سالم و بدون خط و خش',
    insuranceDeadline: '۱۰ ماه',
  },
  {
    id: 2,
    name: 'بی‌ام‌و سری ۷',
    brand: 'BMW',
    modelYear: 2024,
    price: 14200000000,
    mileage: 0,
    color: 'سفید صدفی',
    gearbox: 'Automatic',
    fuelType: 'Hybrid',
    description: 'صفر کیلومتر، پلاک ملی، نیو فیس. مجهز به جدیدترین تکنولوژی‌های روز دنیا و سیستم رانندگی خودکار سطح ۳.',
    images: [
      { url: 'https://picsum.photos/id/234/800/600', alt: 'BMW 7 Series' },
      { url: 'https://picsum.photos/id/235/800/600', alt: 'BMW Interior' },
    ],
    paintStatus: 'بدون رنگ',
    chassisStatus: 'پلمپ',
    bodyStatus: 'سالم',
    insuranceDeadline: '۱۲ ماه',
  },
  {
    id: 3,
    name: 'پورشه کاین توربو',
    brand: 'Porsche',
    modelYear: 2022,
    price: 18500000000,
    mileage: 25000,
    color: 'خاکستری',
    gearbox: 'Automatic',
    fuelType: 'Petrol',
    description: 'قدرت و سرعت بی‌نظیر. سرویس‌ها تماما در نمایندگی انجام شده. کیت اگزوز اسپرت و رینگ‌های ۲۱ اینچی.',
    images: [
      { url: 'https://picsum.photos/id/333/800/600', alt: 'Porsche Cayenne' },
      { url: 'https://picsum.photos/id/334/800/600', alt: 'Porsche Rear' },
      { url: 'https://picsum.photos/id/335/800/600', alt: 'Porsche Interior' },
      { url: 'https://picsum.photos/id/336/800/600', alt: 'Porsche Wheel' },
    ],
    paintStatus: 'یک لکه رنگ جزئی',
    chassisStatus: 'پلمپ',
    bodyStatus: 'لیسه گیری جزئی سپر',
    insuranceDeadline: '۴ ماه',
  },
  {
    id: 4,
    name: 'تویوتا لندکروز',
    brand: 'Toyota',
    modelYear: 2021,
    price: 9800000000,
    mileage: 45000,
    color: 'سفید',
    gearbox: 'Automatic',
    fuelType: 'Petrol',
    description: 'سلطان جاده‌ها. موتور ۶ سیلندر توربو. مناسب برای آفرود و سفرهای طولانی. بسیار تمیز و خانگی.',
    images: [
      { url: 'https://picsum.photos/id/444/800/600', alt: 'Land Cruiser' },
      { url: 'https://picsum.photos/id/445/800/600', alt: 'Land Cruiser Side' },
    ],
    paintStatus: 'بدون رنگ',
    chassisStatus: 'پلمپ',
    bodyStatus: 'سالم',
    insuranceDeadline: '۸ ماه',
  },
  {
    id: 5,
    name: 'هیوندای سانتافه',
    brand: 'Hyundai',
    modelYear: 2018,
    price: 4500000000,
    mileage: 80000,
    color: 'سورمه‌ای',
    gearbox: 'Automatic',
    fuelType: 'Petrol',
    description: 'فول وارداتی، ۶۴ آپشن، دو دیفرانسیل. فنی کاملا سالم به شرط کارشناسی. بیمه ۱۲ ماه.',
    images: [
      { url: 'https://picsum.photos/id/555/800/600', alt: 'Santa Fe' },
      { url: 'https://picsum.photos/id/556/800/600', alt: 'Santa Fe Interior' },
    ],
    paintStatus: 'گلگیر جلو رنگ',
    chassisStatus: 'سالم',
    bodyStatus: 'خط و خش جزئی',
    insuranceDeadline: '۲ ماه',
  },
];